apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "cool-test-app-23-10-02"
  annotations:
    "humanitec.com/orgId": "htc-demo-00"
    "humanitec.com/appId": "cool-test-app-23-10-02"
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
